# Qualitative Results

## Qualitative Results
- 4 long-answer questions
  - What sets EEDC apart?
  - What does EEDC do well?
  - What does EEDC do that's tricky?
  - What should EEDC do differently?
- Lower participation than quantitative questions
  - Out of 178 responses, 103 answered at least one long-answer question

## Positive Themes
- Great culture and values
  - "I love the type of work environment that EEDC have and the Core Values that it stands with."
- Great people
  - "The employees. I have never worked for an organization where I bond with so many colleagues."
- Good internal communication and collaboration between divisions
  - "EEDC does an excellent job facilitating cross organizational collaboration and communication between divisions. This is achieved through meetings such as The Way Forward and the organization of numerous events."

## Positive Themes

- Strong purpose
  - "Our team has the ability to move the needle forward and share in the responsibility and excitement of elevating Edmonton's brand and reputation."
- Does great work
  - "EEDC makes an impact in the city. We have seen some really big successes happen that were either directly influenced by this organization or were at least heavily involved with this organization and its initiatives."

## Improvement Themes
- Policies/processes/systems need improvement
  - "Poor communication & slow payment process of vendor invoices this year, but still feel confident that this will improve."
- Challenging relationship with Shareholder or other public stakeholders
  - "Navigating the constant criticism in the media and at council is difficult."
- Too much change in structure and focus
  - "I've worked in many organizations [...] and EEDC definitely takes the cake on the amount of significant and impactful change that our employees have to try and process."

## Improvement Themes
- Too many meetings and/or meetings not valuable
  - "Internally, The Way Forward and People Leader meetings do not bring strong value. I would prefer having the same info curated and communicated electronically where people have the ability to contribute."
- Mandate/goals not clear
  - "I think EEDC needs to figure out where they're going and remain consistent with decisions."
- Pay/benefits not competitive
  - "Provide compensation packages that are more competitive and reflect increases in workload, responsibility and accountability."
